### ISSUE TITLE
Metric name doesn't make sense: `machine_api_status`

### ISSUE THREAD

**Issue by jewzaam** [openshift/managed-prometheus-exporter-machine-api#6]
It hasn't been changed because the alert for this metric is defined somewhere else.  I didn't want to update two places, which implies to me that having the rule somewhere else was a bad idea.  My bad, I'm sure.

The latest changes here that make this name not make sense were done late on a Friday to fix an issue that was paging SRE.  We wanted a fix before the weekend.  I didn't want to complicate things by renaming metrics across repos.  So it's kept as it is.

Anyway, we need to either track this as debt until we delete this exporter or fix it.  I vote for wait until we delete it when we have metrics from the machine-api operator.

cc @lisa

**Comment by lisa** [comment]
It turns out that this codebase stopped being deployed some time ago, and so therefor this issue can be closed.
